name: Feature request
description: Submit a feature request. This might be a feature you would like to see added, or one you would like to contribute.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to share ideas for new features!
  - type: textarea
    id: feature-desc
    attributes:
      label: Tell us more about this new feature.
      placeholder: I would like to ...
    validations:
      required: true
