name: Comment Slack Notifier

on:
  issue_comment:
    types: [created, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_ISSUE_COMMENT }}
          webhook-type: incoming-webhook
          payload: |
            {
              "action": "${{ github.event.action }}",
              "comment_url": "${{ github.event.comment.html_url }}",
              "content": ${{ toJSON(github.event.comment.body) }}
            }
